server:
  port: 9291

spring:
  application:
    name: API-SERVICE
  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
          - Path=/user/**
        filters:
          - name: CircuitBreaker
            args:
              name: USER-SERVICE
              fallbackuri: forward:/userserviceFallBack
      - id: DEPARTMENT-SERVICE
        uri: lb://DEPARTMENT-SERVICE
        predicates:
          - Path=/departments/**
        filters:
          - name: CircuitBreaker
            args:
              name: DEPARTMENT-SERVICE
              fallbackuri: forward:/deptServiceFallBack

hystrix:
  command:
     fallbackcmd:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 1000



management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream



